<?php
// Web service definitions for local_flwcupkp.

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_flwcupkp_get_frameworks' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_frameworks',
        'classpath' => '',
        'description' => 'List C-UP-KP frameworks.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_framework' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_framework',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP framework.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_competencies' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_competencies',
        'classpath' => '',
        'description' => 'List C-UP-KP competencies.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_competency' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_competency',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP competency.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_use_points' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_use_points',
        'classpath' => '',
        'description' => 'List C-UP-KP Use Points.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_use_point' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_use_point',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP Use Point.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_knowledge_points' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_knowledge_points',
        'classpath' => '',
        'description' => 'List C-UP-KP Knowledge Points.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_knowledge_point' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_knowledge_point',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP Knowledge Point.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_mappings' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_mappings',
        'classpath' => '',
        'description' => 'List C-UP-KP mappings.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_mapping' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_mapping',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP mapping.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_delete_mapping' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'delete_mapping',
        'classpath' => '',
        'description' => 'Delete a C-UP-KP mapping.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_validate_import' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'validate_import',
        'classpath' => '',
        'description' => 'Validate a C-UP-KP JSON package without importing it.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_import_package' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'import_package',
        'classpath' => '',
        'description' => 'Validate and import a C-UP-KP JSON package.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_validate_csv_import' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'validate_csv_import',
        'classpath' => '',
        'description' => 'Validate a C-UP-KP CSV artifact without importing it.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_import_csv' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'import_csv',
        'classpath' => '',
        'description' => 'Validate and import a C-UP-KP CSV artifact.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_record_evidence' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_evidence',
        'classpath' => '',
        'description' => 'Record normalized learner evidence.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_record_flwvrroom_attempt' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_flwvrroom_attempt',
        'classpath' => '',
        'description' => 'Record structured FLW VR Room attempt evidence.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_get_learner_states' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_states',
        'classpath' => '',
        'description' => 'Get learner C-UP-KP states.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_learner_learning_path' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_learning_path',
        'classpath' => '',
        'description' => 'Get learner states and learning-path recommendations.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_recommendations' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_recommendations',
        'classpath' => '',
        'description' => 'Get learner learning-path recommendations.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_evaluation_periods' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_evaluation_periods',
        'classpath' => '',
        'description' => 'List C-UP-KP learner evaluation periods.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_evaluation_period' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_evaluation_period',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP learner evaluation period.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_learner_evaluation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_evaluation',
        'classpath' => '',
        'description' => 'Get a learner C-UP-KP evaluation profile.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_create_evaluation_snapshot' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'create_evaluation_snapshot',
        'classpath' => '',
        'description' => 'Create an immutable learner C-UP-KP evaluation snapshot.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_record_self_evaluation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_self_evaluation',
        'classpath' => '',
        'description' => 'Record a learner self-evaluation for a C-UP-KP target.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_course_evaluation_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_course_evaluation_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP learner evaluation summary metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_coverage_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_coverage_report',
        'classpath' => '',
        'description' => 'Get curriculum coverage report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_orphans_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_orphans_report',
        'classpath' => '',
        'description' => 'Get orphan curriculum records report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_evidence_gaps_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_evidence_gaps_report',
        'classpath' => '',
        'description' => 'Get evidence gap report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_cefr_alignment_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_cefr_alignment_report',
        'classpath' => '',
        'description' => 'Get CEFR alignment report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_import_validation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_import_validation',
        'classpath' => '',
        'description' => 'Get stored import validation details.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_sync_moodle_competencies' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'sync_moodle_competencies',
        'classpath' => '',
        'description' => 'Run Moodle competency sync, dry-run by default.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:synccompetencies',
    ],
    'local_flwcupkp_get_sync_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_sync_status',
        'classpath' => '',
        'description' => 'Get Moodle competency sync readiness.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
];

$services = [
    'FLW C-UP-KP service' => [
        'functions' => array_keys($functions),
        'restrictedusers' => 1,
        'enabled' => 0,
    ],
];
