<?php
// Web service definitions for local_flwcupkp.

defined('MOODLE_INTERNAL') || die();

$functions = [
    'local_flwcupkp_get_frameworks' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_frameworks',
        'classpath' => '',
        'description' => 'List C-UP-KP frameworks.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_framework' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_framework',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP framework.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_competencies' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_competencies',
        'classpath' => '',
        'description' => 'List C-UP-KP competencies.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_competency' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_competency',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP competency.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_use_points' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_use_points',
        'classpath' => '',
        'description' => 'List C-UP-KP Use Points.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_use_point' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_use_point',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP Use Point.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_knowledge_points' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_knowledge_points',
        'classpath' => '',
        'description' => 'List C-UP-KP Knowledge Points.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_knowledge_point' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_knowledge_point',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP Knowledge Point.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_mappings' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_mappings',
        'classpath' => '',
        'description' => 'List C-UP-KP mappings.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_mapping' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_mapping',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP mapping.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_delete_mapping' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'delete_mapping',
        'classpath' => '',
        'description' => 'Delete a C-UP-KP mapping.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_validate_import' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'validate_import',
        'classpath' => '',
        'description' => 'Validate a C-UP-KP JSON package without importing it.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_import_package' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'import_package',
        'classpath' => '',
        'description' => 'Validate and import a C-UP-KP JSON package.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_validate_csv_import' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'validate_csv_import',
        'classpath' => '',
        'description' => 'Validate a C-UP-KP CSV artifact without importing it.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_import_csv' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'import_csv',
        'classpath' => '',
        'description' => 'Validate and import a C-UP-KP CSV artifact.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_record_evidence' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_evidence',
        'classpath' => '',
        'description' => 'Record normalized learner evidence.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_record_flwvrroom_attempt' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_flwvrroom_attempt',
        'classpath' => '',
        'description' => 'Record structured FLW VR Room attempt evidence.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_get_learner_states' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_states',
        'classpath' => '',
        'description' => 'Get learner C-UP-KP states.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_learner_learning_path' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_learning_path',
        'classpath' => '',
        'description' => 'Get learner states and learning-path recommendations.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_recommendations' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_recommendations',
        'classpath' => '',
        'description' => 'Get learner learning-path recommendations.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_evaluation_periods' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_evaluation_periods',
        'classpath' => '',
        'description' => 'List C-UP-KP learner evaluation periods.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_save_evaluation_period' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_evaluation_period',
        'classpath' => '',
        'description' => 'Create or update a C-UP-KP learner evaluation period.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_learner_evaluation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_evaluation',
        'classpath' => '',
        'description' => 'Get a learner C-UP-KP evaluation profile.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_create_evaluation_snapshot' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'create_evaluation_snapshot',
        'classpath' => '',
        'description' => 'Create an immutable learner C-UP-KP evaluation snapshot.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_record_self_evaluation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'record_self_evaluation',
        'classpath' => '',
        'description' => 'Record a learner self-evaluation for a C-UP-KP target.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_course_evaluation_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_course_evaluation_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP learner evaluation summary metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_coverage_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_coverage_report',
        'classpath' => '',
        'description' => 'Get curriculum coverage report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_orphans_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_orphans_report',
        'classpath' => '',
        'description' => 'Get orphan curriculum records report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_evidence_gaps_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_evidence_gaps_report',
        'classpath' => '',
        'description' => 'Get evidence gap report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_cefr_alignment_report' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_cefr_alignment_report',
        'classpath' => '',
        'description' => 'Get CEFR alignment report.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_import_validation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_import_validation',
        'classpath' => '',
        'description' => 'Get stored import validation details.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:import',
    ],
    'local_flwcupkp_sync_moodle_competencies' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'sync_moodle_competencies',
        'classpath' => '',
        'description' => 'Run Moodle competency sync, dry-run by default.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:synccompetencies',
    ],
    'local_flwcupkp_get_sync_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_sync_status',
        'classpath' => '',
        'description' => 'Get Moodle competency sync readiness.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_management_v1_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_management_v1_status',
        'classpath' => '',
        'description' => 'Get the frozen C-UP-KP Management V1 consumer snapshot.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_history_evidence_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_history_evidence_status',
        'classpath' => '',
        'description' => 'Get Program 3 E1 History V1 to C-UP-KP evidence adapter status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_preview_history_evidence_reprocess' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'preview_history_evidence_reprocess',
        'classpath' => '',
        'description' => 'Preview controlled History V1 to C-UP-KP evidence reprocessing.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_history_evidence_reprocess' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_history_evidence_reprocess',
        'classpath' => '',
        'description' => 'Apply controlled History V1 to C-UP-KP evidence reprocessing.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_mastery_state_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_mastery_state_status',
        'classpath' => '',
        'description' => 'Get Program 3 E2 mastery, confidence, and current learner-state status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_current_learner_state' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_current_learner_state',
        'classpath' => '',
        'description' => 'Get the current C-UP-KP learner state with mastery, confidence, and evidence snapshot metadata.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_current_state_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_current_state_summary',
        'classpath' => '',
        'description' => 'Get class-level current C-UP-KP mastery/confidence state metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_preview_mastery_state_rebuild' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'preview_mastery_state_rebuild',
        'classpath' => '',
        'description' => 'Preview a controlled rebuild of C-UP-KP current mastery/confidence states.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_mastery_state_rebuild' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_mastery_state_rebuild',
        'classpath' => '',
        'description' => 'Apply a controlled rebuild of C-UP-KP current mastery/confidence states.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_retention_review_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_retention_review_status',
        'classpath' => '',
        'description' => 'Get Program 3 E3 retention, retrieval, and review status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_current_retention_state' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_current_retention_state',
        'classpath' => '',
        'description' => 'Get the current C-UP-KP learner retention/review state without changing mastery.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_retention_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_retention_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP retention/review metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_preview_retention_review_rebuild' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'preview_retention_review_rebuild',
        'classpath' => '',
        'description' => 'Preview a controlled rebuild of C-UP-KP retention/review states.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_retention_review_rebuild' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_retention_review_rebuild',
        'classpath' => '',
        'description' => 'Apply a controlled rebuild of C-UP-KP retention/review states.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_learning_goal_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learning_goal_status',
        'classpath' => '',
        'description' => 'Get Program 3 A1 competency-centered learning goal status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_current_learning_goal' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_current_learning_goal',
        'classpath' => '',
        'description' => 'Get the current competency-centered learning goal for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_learning_goal_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_learning_goal_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP learning goal metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learning_goal_options' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learning_goal_options',
        'classpath' => '',
        'description' => 'Get C-UP-KP target options for competency-centered learning goals.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_save_learning_goal' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'save_learning_goal',
        'classpath' => '',
        'description' => 'Save a versioned competency-centered learning goal.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_placement_diagnostic_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_placement_diagnostic_status',
        'classpath' => '',
        'description' => 'Get Program 3 A2 placement diagnostic and cold-start status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_current_placement_diagnostic' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_current_placement_diagnostic',
        'classpath' => '',
        'description' => 'Get the current placement diagnostic state for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_placement_diagnostic_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_placement_diagnostic_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP placement diagnostic metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_preview_placement_diagnostic_reprocess' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'preview_placement_diagnostic_reprocess',
        'classpath' => '',
        'description' => 'Preview controlled History V1 placement diagnostic reprocessing.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_placement_diagnostic_reprocess' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_placement_diagnostic_reprocess',
        'classpath' => '',
        'description' => 'Apply controlled History V1 placement diagnostic reprocessing.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:manageframeworks',
    ],
    'local_flwcupkp_get_adaptive_decision_policy_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_adaptive_decision_policy_status',
        'classpath' => '',
        'description' => 'Get Program 3 A3 adaptive decision policy status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_adaptive_decision' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_adaptive_decision',
        'classpath' => '',
        'description' => 'Get the current explainable C-UP-KP adaptive decision for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_adaptive_decision_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_adaptive_decision_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP adaptive decision policy metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_goal_gap_path_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_goal_gap_path_status',
        'classpath' => '',
        'description' => 'Get Program 3 A4 goal-gap and initial personalized path status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_initial_path' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_initial_path',
        'classpath' => '',
        'description' => 'Get an explainable C-UP-KP goal-gap and initial personalized path for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_initial_path_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_initial_path_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP goal-gap and initial path metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_candidate_activity_resolution_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_candidate_activity_resolution_status',
        'classpath' => '',
        'description' => 'Get Program 3 A4B candidate eligibility and activity-resolution status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_activity_resolution' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_activity_resolution',
        'classpath' => '',
        'description' => 'Resolve an explainable C-UP-KP candidate target to eligible Moodle activities for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_activity_resolution_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_activity_resolution_summary',
        'classpath' => '',
        'description' => 'Get class-level C-UP-KP candidate activity-resolution metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_adaptive_path_engine_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_adaptive_path_engine_status',
        'classpath' => '',
        'description' => 'Get Program 3 A5 continuous adaptive path engine status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_adaptive_path' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_adaptive_path',
        'classpath' => '',
        'description' => 'Preview the current explainable A5 adaptive path for a learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_apply_learner_adaptive_path' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_learner_adaptive_path',
        'classpath' => '',
        'description' => 'Apply an idempotent A5 adaptive recommendation refresh for one learner.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_get_class_adaptive_path_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_adaptive_path_summary',
        'classpath' => '',
        'description' => 'Get class-level A5 adaptive path and refresh metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_class_adaptive_paths' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_class_adaptive_paths',
        'classpath' => '',
        'description' => 'Apply idempotent A5 adaptive recommendation refreshes for a class scope.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_get_trajectory_simulation_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_trajectory_simulation_status',
        'classpath' => '',
        'description' => 'Get Program 3 A5B trajectory simulation and invariant status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_run_trajectory_simulation' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'run_trajectory_simulation',
        'classpath' => '',
        'description' => 'Run a bounded deterministic, read-only A5B trajectory simulation suite.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_trajectory_projection' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_trajectory_projection',
        'classpath' => '',
        'description' => 'Get a read-only A5B counterfactual trajectory projection for one learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_progress_readiness_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_progress_readiness_status',
        'classpath' => '',
        'description' => 'Get Program 3 A5C progress and goal-readiness contract status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learner_progress_readiness' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_progress_readiness',
        'classpath' => '',
        'description' => 'Get separate completion, mastery, goal-readiness, and path metrics for one learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_class_progress_readiness_summary' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_class_progress_readiness_summary',
        'classpath' => '',
        'description' => 'Get class-level semantic goal-readiness and qualitative milestone metrics.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_learning_timeline_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learning_timeline_status',
        'classpath' => '',
        'description' => 'Get Program 3 UX1 Past, Present, and Future dashboard contract status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_student_learning_timeline' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_student_learning_timeline',
        'classpath' => '',
        'description' => 'Get the read-only StudentLearningTimelineView for one authorized learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_learner_experience_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_learner_experience_status',
        'classpath' => '',
        'description' => 'Get Program 3 UX2 learner-experience simplification contract status.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_simplified_learner_experience' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_simplified_learner_experience',
        'classpath' => '',
        'description' => 'Get the read-only simplified learner experience for one authorized learner.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewlearnerpath',
    ],
    'local_flwcupkp_get_staff_intelligence_status' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_staff_intelligence_status',
        'classpath' => '',
        'description' => 'Get Program 3 UX3 staff intelligence and intervention readiness.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_get_staff_intelligence' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'get_staff_intelligence',
        'classpath' => '',
        'description' => 'Get detailed C-UP-KP explainability for one learner and authorized staff member.',
        'type' => 'read',
        'capabilities' => 'local/flwcupkp:viewreports',
    ],
    'local_flwcupkp_apply_staff_intervention' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'apply_staff_intervention',
        'classpath' => '',
        'description' => 'Apply a permission-controlled, versioned, audited UX3 learner intervention.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
    'local_flwcupkp_release_staff_intervention' => [
        'classname' => 'local_flwcupkp\external\api',
        'methodname' => 'release_staff_intervention',
        'classpath' => '',
        'description' => 'Release an active UX3 intervention by appending an immutable version.',
        'type' => 'write',
        'capabilities' => 'local/flwcupkp:override',
    ],
];

$services = [
    'FLW C-UP-KP service' => [
        'functions' => array_keys($functions),
        'restrictedusers' => 1,
        'enabled' => 0,
    ],
];
